---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-express
  labels:
    app: mongo-express
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
