apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-express
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/local2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
