---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  labels:
    app: mongodb
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

