apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-express
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db2"

